plugin: aws_ec2
regions:
  - eu-central-1
hostnames:
  - 'tag:Name'
compose:
  ansible_host: public_dns_name
  ansible_user: "'ubuntu'"
  ansible_ssh_private_key_file: "{{ lookup('ansible.builtin.env', 'SSH_PRIVATE') }}"