variables:
  PROD_CONTAINER_NAME: demoapp
  PROD_CONTAINER_IMAGE: "atom363/demoapp:python-web-app-1.0"
  TF_VAR_VMNAME: diploma
  # IMAGE_NAME: atom363/demoapp
  # IMAGE_TAG: python-web-app-1.0
  # PROD_IP: 18.194.123.248

stages:
  - test
  - build
  - deploy_infra
  - deploy_app

test_app:
  stage: test
  image: python:3.9-slim-buster
  before_script:
    - apt-get update && apt-get install make
  script:
    - cd ./app/
    - make test

build_image:
  stage: build
  image: docker:20.10.22
  services:
    - docker:20.10.22-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
  script:
    - docker build -t $PROD_CONTAINER_IMAGE ./app/
    - docker push $PROD_CONTAINER_IMAGE

deploy_infrastructure:
  stage: deploy_infra
  image: 
    name: hashicorp/terraform:1.3.7
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - cd ./infrastructure/tf/
    - terraform init -input=false
    - terraform plan
    - terraform apply -auto-approve
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

deploy_application:
  stage: deploy_app
  image: ubuntu:22.04
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -qy ansible python3 python3-pip
    - pip3 install boto3
    - echo "$SSH_KEY_AWS" > "$(pwd)/aws_ssh.pem"
    - export ANSIBLE_HOST_KEY_CHECKING=False
  script:
    - ansible-playbook ./infrastructure/ansible/app_role/playbook.yml -i ./infrastructure/ansible/app_role/aws_ec2.yml --key-file "$(pwd)/aws_ssh.pem"
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

# deploy:
#   stage: deploy
#   before_script:
#     - chmod 400 $SSH_KEY_AWS
#   script:
#     - ssh -o StrictHostKeyChecking=no -i $SSH_KEY_AWS ubuntu@$PROD_IP "
#         sudo docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS &&
#         sudo docker ps -aq | xargs docker stop | xargs docker rm &&
#         sudo docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG"
#   rules:
#     - if: $CI_COMMIT_BRANCH == "master"
